---
id: docker-meetup-kansai-5
base_name: docker-ruby-image-official
tags:
- ruby
- docker
presentation_date: 2019/11/22
version: 2019.11.22
licenses: []
slideshare_id: dockerruby
speaker_deck_id: dockerfalseohuisiyarurubyimezitoha
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
